Avoid keeping activities in memory for a long time before updating
This is to avoid errors like
Failed to update PipelineActivity: Operation cannot be fulfilled on pipelineactivities.jenkins.io "jenkins-x-tests-bdd-test-spring-1538663830-master-1": the object has been modified; please apply your changes to the latest version and try again
        error: Operation cannot be fulfilled on pipelineactivities.jenkins.io "jenkins-x-tests-bdd-test-spring-1538663830-master-1": the object has been modified; please apply your changes to the latest version and try again

Fixes #1890