fix: Import from non dev team namespace
This fixes a regression appearing with the introduction of prow that made
import and other commands calling ImportOptions.Run with another team
namespace than dev as the current namespace fail with:

error: no environment with name 'dev' found