jx promote fails outside of a git working copy
`error: PromoteStepActivityKey was not valid`

In a git working dir (any git, not necessarily the same project we are promoting)

```
$ jx promote croc-hunter-jenkinsx --version 0.0.16 --env production
prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/jx/issues/2410
Promoting app croc-hunter-jenkinsx version 0.0.16 to namespace jx-production
No $BUILD_NUMBER environment variable found so cannot record promotion activities into the PipelineActivity resources in kubernetes
No changes made to the GitOps Environment source code. Code must be up to date!
```

Outside a git working copy

```
$ jx promote croc-hunter-jenkinsx --version 0.0.16 --env production
prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/jx/issues/2410
Promoting app croc-hunter-jenkinsx version 0.0.16 to namespace jx-production
Could not discover the Git repository info failed to parse Git URL  due to Invalid path  could not determine organisation and repository name
failed to get the git branch name in dir .
No $JOB_NAME environment variable found so cannot record promotion activities into the PipelineActivity resources in kubernetes
No changes made to the GitOps Environment source code. Code must be up to date!
Failed to update PipelineActivity: PromoteStepActivityKey was not valid
error: PromoteStepActivityKey was not valid
```